// Generates src/generated.ts — the canonical tokens.css inlined as a string,
// plus a data-URI @font-face variant so web-core can inject fully self-contained
// styles into a shadow root with zero runtime fetches (F1-D19).
import { readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const here = dirname(fileURLToPath(import.meta.url));
const pkgRoot = join(here, '..');

const rawCss = readFileSync(join(pkgRoot, 'tokens.css'), 'utf8');

const fontFiles = [
  ['JetBrains Mono', 400, 'jetbrains-mono-400.woff2'],
  ['JetBrains Mono', 500, 'jetbrains-mono-500.woff2'],
  ['JetBrains Mono', 600, 'jetbrains-mono-600.woff2'],
  ['Inter', 400, 'inter-400.woff2'],
  ['Inter', 500, 'inter-500.woff2'],
  ['Inter', 600, 'inter-600.woff2'],
  ['Schibsted Grotesk', 400, 'schibsted-grotesk-400.woff2'],
  ['Schibsted Grotesk', 600, 'schibsted-grotesk-600.woff2'],
  ['Schibsted Grotesk', 700, 'schibsted-grotesk-700.woff2'],
];

// Build data-URI @font-face rules (self-contained; no relative URL to resolve).
const dataUriFaces = fontFiles
  .map(([family, weight, file]) => {
    const b64 = readFileSync(join(pkgRoot, 'fonts', file)).toString('base64');
    return `@font-face {
  font-family: '${family}';
  font-style: normal;
  font-weight: ${weight};
  font-display: swap;
  src: url('data:font/woff2;base64,${b64}') format('woff2');
}`;
  })
  .join('\n');

// Split the CSS: the @font-face block (heavy, font bytes) vs. the token rules.
// This keeps `tokensCss` (the core string, counted against the ≤35KB budget) free
// of font bytes, while `fontFaceCss` carries the self-hosted data-URI fonts that
// web-core also injects (F1-D19). The size-check excludes fontFaceCss (F1-D15:
// "excluding font files").
const faceBlockStart = rawCss.indexOf('@font-face');
const rootStart = rawCss.indexOf(':root {');
const head = rawCss.slice(0, faceBlockStart);
const tail = rawCss.slice(rootStart);
const tokensOnlyCss = `${head}${tail}`;

const escapeTemplate = (s) =>
  s.replace(/\\/g, '\\\\').replace(/`/g, '\\`').replace(/\$\{/g, '\\${');

const out = `// AUTO-GENERATED by scripts/generate.mjs — do not edit by hand.
// Source of truth: packages/tokens/tokens.css + packages/tokens/fonts/*.woff2.

/** The canonical design tokens as a CSS string (colour/type/spacing/radius/motion
 *  vars + theme). Font-face rules are kept separate in \`fontFaceCss\` so the core
 *  bundle stays inside the ≤35KB gzip budget (F1-D15,D17). Inject BOTH into the
 *  shadow root. */
export const tokensCss = \`${escapeTemplate(tokensOnlyCss)}\`;

/** Self-hosted subset fonts as data-URI @font-face rules (F1-D19): JetBrains Mono
 *  + Inter, no runtime fetch. Heavy (font bytes) and EXCLUDED from the core size
 *  budget. Inject alongside \`tokensCss\`. */
export const fontFaceCss = \`${escapeTemplate(dataUriFaces)}\`;
`;

writeFileSync(join(pkgRoot, 'src', 'generated.ts'), out);
console.log('generated src/generated.ts (%d bytes)', out.length);
