import { readFile, writeFile } from 'node:fs/promises';
import { join } from 'node:path';
import { defaultApiUrl } from './config.js';

/**
 * `signal init` (F2-D8) — the one-time Web SDK install for a web/npm project. It:
 *   1. detects a web/npm project (a `package.json` in the target dir),
 *   2. adds `@signal/web` to its dependencies (idempotent — skips if present),
 *   3. writes a small `signal-setup.js` wiring snippet that calls
 *      `Signal.init(publishableKey)` (idempotent — never duplicated), and
 *   4. prints next steps (install + import the snippet).
 *
 * It is deliberately conservative (edge cases in the plan): it never rewrites the
 * host's own entry/source files (guessing wrong is worse than a manual step), and
 * an ambiguous/unknown project (no package.json) prints manual steps instead of
 * guessing. SDK-install for native surfaces is out of scope here.
 */

/** The dependency spec written into package.json. Kept as a caret range so a
 *  published `@signal/web` resolves; within this monorepo it is a workspace pkg. */
export const WEB_SDK_DEP = '@ashish221/signal-web';
export const WEB_SDK_VERSION = '^0.1.0';

const SETUP_FILENAME = 'signal-setup.js';

export interface InitResult {
  /** 'web' when a package.json was found; 'unknown' → manual steps printed. */
  projectType: 'web' | 'unknown';
  depAdded: boolean;
  depAlreadyPresent: boolean;
  snippetWritten: boolean;
  snippetAlreadyPresent: boolean;
  files: string[];
}

interface PackageJson {
  name?: string;
  dependencies?: Record<string, string>;
  [k: string]: unknown;
}

function setupSnippet(publishableKey: string): string {
  return `// Signal Web SDK setup (generated by \`signal init\`, F2-D8).
// Import this once at your app's entry point, e.g. \`import './${SETUP_FILENAME}';\`.
import { Signal } from '${WEB_SDK_DEP}';

// Your account's publishable key (safe to ship in client code). \`apiUrl\` points at
// the Signal API — the SDK calls it cross-origin from your site.
Signal.init('${publishableKey}', { apiUrl: '${defaultApiUrl()}' });

// Then, wherever a meaningful moment happens, record it:
//   Signal.track('checkout_completed');
`;
}

/**
 * Run the init flow against `dir`. `out` receives human-readable lines. Returns a
 * structured result so tests (and the caller) can assert what changed. Never
 * throws on a missing project — it reports `unknown` and prints manual steps.
 */
export async function runInit(
  dir: string,
  publishableKey: string,
  out: (line: string) => void,
): Promise<InitResult> {
  const pkgPath = join(dir, 'package.json');
  let pkg: PackageJson | null = null;
  try {
    pkg = JSON.parse(await readFile(pkgPath, 'utf8')) as PackageJson;
  } catch {
    pkg = null;
  }

  if (!pkg) {
    out('No package.json found — this does not look like a web/npm project.');
    out('Manual setup:');
    out(`  1. Install the SDK:   npm install ${WEB_SDK_DEP}`);
    out(`  2. In your entry file: import { Signal } from '${WEB_SDK_DEP}';`);
    out(
      `                          Signal.init('${publishableKey}', { apiUrl: '${defaultApiUrl()}' });`,
    );
    out("  3. Record moments:     Signal.track('checkout_completed');");
    return {
      projectType: 'unknown',
      depAdded: false,
      depAlreadyPresent: false,
      snippetWritten: false,
      snippetAlreadyPresent: false,
      files: [],
    };
  }

  const files: string[] = [];

  // 2) Add the dependency (idempotent).
  pkg.dependencies ??= {};
  const depAlreadyPresent = WEB_SDK_DEP in pkg.dependencies;
  let depAdded = false;
  if (!depAlreadyPresent) {
    pkg.dependencies[WEB_SDK_DEP] = WEB_SDK_VERSION;
    await writeFile(pkgPath, `${JSON.stringify(pkg, null, 2)}\n`);
    depAdded = true;
    files.push('package.json');
    out(`Added ${WEB_SDK_DEP}@${WEB_SDK_VERSION} to package.json dependencies.`);
  } else {
    out(`${WEB_SDK_DEP} is already a dependency — skipping (no duplicate).`);
  }

  // 3) Write the init wiring snippet (idempotent — don't clobber an existing one).
  const setupPath = join(dir, SETUP_FILENAME);
  let snippetWritten = false;
  let snippetAlreadyPresent = false;
  try {
    await readFile(setupPath, 'utf8');
    snippetAlreadyPresent = true;
    out(`${SETUP_FILENAME} already exists — leaving it untouched.`);
  } catch {
    await writeFile(setupPath, setupSnippet(publishableKey));
    snippetWritten = true;
    files.push(SETUP_FILENAME);
    out(`Wrote ${SETUP_FILENAME} with your Signal.init(...) wiring.`);
  }

  // 4) Next steps.
  out('');
  out('Next steps:');
  out(`  1. Install deps:      npm install   (or pnpm install / yarn)`);
  out(`  2. Import the setup:  import './${SETUP_FILENAME}';   // once, at your entry point`);
  out(`  3. Record a moment:   Signal.track('checkout_completed');`);

  return {
    projectType: 'web',
    depAdded,
    depAlreadyPresent,
    snippetWritten,
    snippetAlreadyPresent,
    files,
  };
}
